#!/bin/bash
## This is a program written by TriVoxel (https://trivoxel.page.link/site)
## Made for LionOS - A free, open source Linux distribution (https://lionos.org)
## Installs programs using a custom version of the Apt software.

### Variables ###
self=$0
var=$1
pkg=$(echo "$*" | cut -d " " -f2-)
cnf="0"

### Functions ###
.elevPriv () { #increases privileges if not root
  if [ $EUID != 0 ]; then
    sudo "$self" "$@"
    #exit $?
  fi
}
.noConfirm () {
  if ($cnf = 1); then
    return -y
  fi
}
.setConfirm () {
  cnf="1"
}
.fetch () {
  .elevPriv
  sudo apt-get install $pkg
}
.update () {
  .elevPriv
  sudo apt-get update $(.noConfirm) $pkg
}
.upgrade () {
  .elevPriv
  sudo apt-get upgrade
}
.autoRemove () {
  .elevPriv
  sudo apt-get autoremove $pkg
}
.purge () {
  .elevPriv
  sudo apt-get purge $pkg
}
.addRepo () {
  .elevPriv
  sudo apt-add-repository $pkg
}
.remRepo () {
  .elevPriv
  sudo add-apt-repository --remove $pkg
}
.version () {
  echo "\
   /\\_/\\
  ( o.o )      Roar Version 1.0
    / \\   __   Developed by TriVoxel
   (___)_/  '"
  exit
}
case "$1" in
  -H|-h|--help)
    if [ -z $2 ]; then
      echo "Roar help:
Usage: roar <operation+option> [...]
  Example: roar -Ugn
Operations:
  roar {-H --help} <operation>     >> displays help dialogue
  roar {-V --version}              >> displays version information
  roar {-F --fetch} <package(s)>   >> installs selected package(s)
  roar {-R --remove} <package(s)>  >> removes selected package(s)
  roar {-U --update}               >> updates the system
  roar {-G --upgrade}              >> upgrades the system
  roar {-S --search} <query>       >> searches repositories for package(s)
  roar {-O --repo} <ppa>           >> adds Ubuntu/Debian PPAs
Use 'roar -H <operation>' for extended information on it'"
    else
      case "$2" in
        -H|--help)
          echo "Usage: roar {-H --help} <operation>
Description: displays help dialogue.

Options:
  roar -H {-H --help}              >> displays help dialogue for 'help' operation
  roar -H {-V --version}           >> displays help dialogue for 'version' operation
  roar -H {-F --fetch}             >> displays help dialogue for 'fetch' operation
  roar -H {-R --remove}            >> displays help dialogue for 'remove' operation
  roar -H {-U --update}            >> displays help dialogue for 'update' operation
  roar -H {-G --upgrade}           >> displays help dialogue for 'upgrade' operation
  roar -H {-S --search}            >> displays help dialogue for 'search' operation
  roar -H {-O --repo}              >> displays help dialogue for 'repo' operation"
          ;;
        -V|--version)
          echo "Usage: roar {-V --version}
Description: displays version information"
          ;;
        -F|--fetch)
          echo "Usage: roar {-F*} <package(s)>
Description: installs selected package(s)
Options:
  roar -Fn <package(s)>            >> don't require pressing 'Y' to install packages
  roar -Fl                         >> lists packages
  roar -Fe <package(s)>            >> reinstall packages"
          ;;
        -R|--remove)
          echo "Usage: roar {-R*} <package(s)>
Description: removes selected package(s)
Options:
  roar -Rn <package(s)>            >> don't require pressing 'Y' to install packages"
          ;;
        -U|--upgrade)
          echo "Usage: roar {-U*} <package(s)>
Description: updates the system
Options:
  roar -Un                         >> don't require pressing 'Y' to install packages
  roar -Ug                         >> update the system then install updates
  roar -Ugn                        >> update the system then install updates without pressing 'Y'"
          ;;
        -G|--upgrade)
          echo "Usage: roar {-G*} <package(s)>
Description: upgrades the system
Options:
  roar -Gn                         >> don't require pressing 'Y' to install packages
  roar -Gu                         >> update the system then install updates
  roar -Gun                        >> update the system then install updates without pressing 'Y'"
          ;;
        -S|--search)
          echo "Usage: roar {-S} <query>
Description: searches repositories for packages."
          ;;
        -O|--repo)
          echo "Usage: roar {-O} <ppa>
Description: adds Debian/Ubuntu PPAs"
          ;;
      esac
    fi
    ;;
  -V|-v|--version)
    .version
    ;;
  # Fetch
  -F|--fetch)
    .fetch
    ;;
  -Fn)
    .setConfirm
    .fetch
    ;;
  # Repo
  -O|--repo)
    .addRepo
    ;;
  -On)
    .setConfirm
    .addRepo
    ;;
  -Or)
    .remRepo
    ;;
  -Orn)
    .setConfirm
    .remRepo
    ;;
  # Remove
  -R|--remove)
    .remove
    ;;
  # Update
  -U|--update)
    .update
    ;;
  -Un)
    .setConfirm
    .update
    ;;
  # Upgrade
  -G|--upgrade)
    .upgrade
    ;;
  -Gn)
    .setConfirm
    .upgrade
    ;;
  # Update & Upgrade
  -Ug|-Gu)
    .update
    .upgrade
    ;;
  -Ugn|-Gun)
    .setConfirm
    .update
    .upgrade
    ;;
  #-T|-t|--test)
  #  echo "Output" "$pkg"
  #  ;;
esac
exit
