#!/bin/bash
## This is a program written by TriVoxel (https://trivoxel.page.link/site)
## Made for LionOS - A free, open source Linux distribution (https://lionos.org)
## Installs programs using a custom version of the Apt software.

### Variables ###
ver="1.0"
slf=$0
opr=$1
cnf="0"

## Generates the packages list
if [[ ! -z $2 ]]; then
  pkg=$(echo "$*" | cut -d " " -f2-) # Maybe a bit hacky but gets the job done
else
  pkg=$2
fi

### Functions ###
.complete () {
  return 100 # Completed commands return 100 for error detection
}
.elevPriv () { #increases privileges if not root
  if [ $EUID != 0 ]; then
    sudo "$slf" "$@"
  fi
}
.noConfirm () {
  if [ $cnf = 1 ]; then
    echo "-y"
  fi
}
.setConfirm () {
  cnf="1"
}
.fetch () {
  echo "\
 /\\_/\\   Preparing to fetch
( ^-^ )  selected packages!!" && sleep 1
  sudo apt-get install $(.noConfirm) $pkg
}
.refetch () {
  echo "\
 /\\_/\\   Preparing to fetch
( ^-^ )  selected packages!!" && sleep 1
  sudo apt-get install $(.noConfirm) --reinstall $pkg
}
.remove () {
  echo "\
 /\\_/\\   Preparing to remove
( ;-; )  selected packages!!" && sleep 1
  sudo apt-get remove $(.noConfirm) $pkg
}
.fetchList () {
  echo "\
 /\\_/\\   Preparing to list
( -.-*)  installed packages!!" && sleep 1
  apt list --installed
}
.update () {
  echo "\
 /\\_/\\   Preparing to update
( @-@!)  all your packages!!" && sleep 1
  sudo apt-get update $(.noConfirm)
}
.upgrade () {
  echo "\
 /\\_/\\   Preparing to upgrade
( o-o')  all your packages!!" && sleep 1
  sudo apt-get upgrade $(.noConfirm) $pkg
}
.autoRemove () {
  echo "\
 /\\_/\\   Preparing to autoremove
( ;.; )  selected packages!!" && sleep 1
  sudo apt-get autoremove $(.noConfirm) $pkg
}
.purge () {
  echo "\
 /\\_/\\   Preparing to purge
( x x )  selected packages!!" && sleep 1
  sudo apt-get purge $(.noConfirm) $pkg
}
.addRepo () {
  echo "\
 /\\_/\\   Preparing to add the
( 0.0 )  selected repository!!" && sleep 1
  sudo apt-add-repository $(.noConfirm) $pkg
}
.remRepo () {
  echo "\
 /\\_/\\   Preparing to remove the
( 0n0 )  selected repository!!" && sleep 1
  sudo add-apt-repository --remove $(.noConfirm) $pkg
}
.version () {
  echo "\
 /\\_/\\
( -.o )      Roar Version $ver
  / \\   __   Developed by TriVoxel
 (___)_/  '"
  .complete
}

### Logic ###
case "$1" in
  -H|-h|--help)
    if [ -z $2 ]; then
      echo "Usage: roar <operation+option> [...]
  Example: roar -Ugn
Operations:
  roar {-H --help} <operation>     >> displays help dialogue
  roar {-V --version}              >> displays version information
  roar {-F --fetch} <package(s)>   >> installs selected package(s)
  roar {-R --remove} <package(s)>  >> removes selected package(s)
  roar {-U --update}               >> updates the system
  roar {-G --upgrade}              >> upgrades the system
  roar {-S --search} <query>       >> searches repositories for package(s)
  roar {-O --repo} <ppa>           >> adds Ubuntu/Debian PPAs
Use 'roar -H <operation>' for extended information on it
  Example: roar -H --help"
    else
      case "$2" in
        -H|--help)
          echo "Usage: roar {-H --help} <operation>
Description: displays help dialogue.
Options:
  roar -H {-H --help}              >> displays help dialogue for 'help' operation
  roar -H {-V --version}           >> displays help dialogue for 'version' operation
  roar -H {-F --fetch}             >> displays help dialogue for 'fetch' operation
  roar -H {-R --remove}            >> displays help dialogue for 'remove' operation
  roar -H {-U --update}            >> displays help dialogue for 'update' operation
  roar -H {-G --upgrade}           >> displays help dialogue for 'upgrade' operation
  roar -H {-S --search}            >> displays help dialogue for 'search' operation
  roar -H {-O --repo}              >> displays help dialogue for 'repo' operation"
          ;;
        -V|--version)
          echo "Usage: roar {-V --version}
Description: displays version information"
          ;;
        -F|--fetch)
          echo "Usage: roar {-F*} <package(s)>
Description: installs selected package(s)
Options:
  roar -Fn <package(s)>            >> don't require consent to fetch selected package(s)
  roar -Fe <package(s)>            >> refetch selected package(s) without consent
  roar -Fen <package(s)>           >> refetch selected package(s) without consent
  roar -Fl                         >> lists installed packages"
          ;;
        -R|--remove)
          echo "Usage: roar {-R*} <package(s)>
Description: removes selected package(s)
Options:
  roar -Rn <package(s)>            >> don't require consent to install packages
  roar -Ra <package(s)>            >> automatically removes unneeded packages
  roar -Ran <package(s)>           >> automatically removes unneeded packages without consent
  roar -Rp <package(s)>            >> purge all of package(s) files and directories
  roar -Rpn <package(s)>           >> purge all of package(s) files and directories without consent
  roar -Ro <package(s)> <ppa>      >> removes selected PPA
  roar -Ron <package(s)>           >> removes selected PPA without consent"
          ;;
        -U|--upgrade)
          echo "Usage: roar {-U*} <package(s)>
Description: updates the system
Options:
  roar -Un                         >> don't require consent to download updates
  roar -Ug                         >> update the system then install updates
  roar -Ugn                        >> update the system then install updates without consent"
          ;;
        -G|--upgrade)
          echo "Usage: roar {-G*} <package(s)>
Description: upgrades the system
Options:
  roar -Gn                         >> don't require confirmation to install updates
  roar -Gu                         >> update the system then install updates
  roar -Gun                        >> update the system then install updates without consent"
          ;;
        -S|--search)
          echo "Usage: roar {-S} <query>
Description: searches repositories for packages."
          ;;
        -O|--repo)
          echo "Usage: roar {-O*} <ppa>
Description: adds Debian/Ubuntu PPAs
Options:
  roar -On                         >> adds Debian/Ubuntu PPA without consent
  roar -Or                         >> removes selected PPA
  roar -Orn                        >> removes selected PPA without consent"
          ;;
      esac
    fi
    ;;
  -V|-v|--version)
    .version
    ;;
  # Fetch
  -F|--fetch)
    .fetch
    ;;
  -Fn)
    .setConfirm && .fetch
    ;;
  -Fe)
    .refetch
    ;;
  -Fen)
    .setConfirm && .refetch
    ;;
  -Fl)
    .fetchList
    ;;
  # Repo
  -O|--repo)
    .addRepo
    ;;
  -On)
    .setConfirm && .addRepo
    ;;
  -Or)
    .remRepo
    ;;
  -Orn)
    .setConfirm && .remRepo
    ;;
  # Remove
  -R|--remove)
    .remove
    ;;
  -Rn)
    .setConfirm && .remove
    ;;
  -Ra)
    .autoRemove
    ;;
  -Ran)
    .setConfirm && .autoRemove
    ;;
  -Rp)
    .purge
    ;;
  -Rpn)
    .setConfirm && .purge
    ;;
  -Ro)
    .remRepo
    ;;
  -Ron)
    .setConfirm && .remRepo
    ;;
  # Update
  -U|--update)
    .update
    ;;
  -Un)
    .setConfirm && .update
    ;;
  # Upgrade
  -G|--upgrade)
    .upgrade
    ;;
  -Gn)
    .setConfirm && .upgrade
    ;;
  # Update & Upgrade
  -Ug|-Gu)
    .update && .upgrade
    ;;
  -Ugn|-Gun)
    .setConfirm && .update && .upgrade
    ;;
esac
